x-veld:
  code:
    description: "apply NER models on linkedcat data for usage of the inferenced entites in the 
      AKP project"
    topics:
      - "NLP"
      - "Machine learning"
      - "Named entity recognition"

    inputs:
      - volume: /veld/input/
        file_type: "spacy model"
        contents:
          - "NLP model"
          - "NER model"

    outputs:
      - volume: /veld/output/
        file_type: "csv"
        environment: out_csv_file
        description: "inferenced NLP / NER data."
        contents:
          - "inferenced NLP data"
          - "NLP data"
          - "NER data"

    settings:
      - environment: solr_core_url
        description: "url pointing to a solr core from where text data should be loaded"
        env_type: "url"

services:
  veld_infer:
    build: .
    command: jupyter notebook --ip='*' --allow-root --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src:/veld/code/
    environment:
      solr_core_url: null
      out_csv_file: null

